apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels:
    app: department-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-app
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      containers:
      - name: department-service-app
        image: shubham01/department:0.0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
spec:
  selector:
    app: department-service-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9001